export const loginApi = "https://api.escuelajs.co/api/v1/auth/login"
export const signUpApi = "https://api.escuelajs.co/api/v1/users/"
export const productApi = "https://api.escuelajs.co/api/v1/products"
export const searchItemApi = "https://api.escuelajs.co/api/v1/products/?title="
export const categoryApi = "https://api.escuelajs.co/api/v1/categories/"